export const clerkAppearance = {
  variables: {
    colorPrimary: "#17a89b",
    colorText: "#123047",
    colorBackground: "#ffffff",
    colorInputBackground: "#f8fafb",
    colorInputText: "#123047",
    colorTextSecondary: "#607484",
    colorNeutral: "#123047",
    borderRadius: "16px",
    fontFamily: "Arial, Helvetica, sans-serif",
  },
  elements: {
    rootBox: "clerk-root",
    cardBox: "clerk-card-box",
    card: "clerk-card",
    main: "clerk-main",
    header: "clerk-hidden",
    footer: "clerk-footer",
    footerAction: "clerk-footer-action",
    footerActionText: "clerk-footer-text",
    footerActionLink: "clerk-link",
    form: "clerk-form",
    formField: "clerk-field",
    formFieldRow: "clerk-field-row",
    formFieldLabelRow: "clerk-label-row",
    formButtonPrimary: "clerk-primary",
    socialButtonsBlockButton: "clerk-social",
    socialButtonsBlockButtonText: "clerk-social-text",
    dividerLine: "clerk-divider",
    dividerText: "clerk-divider-text",
    formFieldInput: "clerk-input",
    formFieldLabel: "clerk-label",
    formFieldInputShowPasswordButton: "clerk-password-toggle",
    formFieldCheckboxInput: "clerk-checkbox",
    formFieldCheckboxLabel: "clerk-checkbox-label",
    formFieldCheckboxLabelButton: "clerk-link",
    formFieldErrorText: "clerk-error",
    formFieldSuccessText: "clerk-success",
    alert: "clerk-alert",
    identityPreview: "clerk-identity-preview",
  },
};
