export const clerkAppearance = {
  variables: {
    colorPrimary: "#07594c",
    colorText: "#073f36",
    colorBackground: "#fffdf8",
    colorInputBackground: "#fffdf8",
    colorInputText: "#073f36",
    colorTextSecondary: "#546a64",
    colorNeutral: "#073f36",
    borderRadius: "12px",
    fontFamily: "Arial, Helvetica, sans-serif",
  },
  elements: {
    rootBox: "clerk-root",
    cardBox: "clerk-card-box",
    card: "clerk-card",
    main: "clerk-main",
    header: "clerk-hidden",
    footer: "clerk-footer",
    footerAction: "clerk-footer-action",
    footerActionText: "clerk-footer-text",
    footerActionLink: "clerk-link",
    form: "clerk-form",
    formFieldRow: "clerk-field-row",
    formButtonPrimary: "clerk-primary",
    socialButtonsBlockButton: "clerk-social",
    socialButtonsBlockButtonText: "clerk-social-text",
    dividerLine: "clerk-divider",
    dividerText: "clerk-divider-text",
    formFieldInput: "clerk-input",
    formFieldLabel: "clerk-label",
    formFieldInputShowPasswordButton: "clerk-password-toggle",
    formFieldCheckboxInput: "clerk-checkbox",
    formFieldCheckboxLabel: "clerk-checkbox-label",
    formFieldCheckboxLabelButton: "clerk-link",
  },
};
